project_path: .
model_name: default
read_format: parquet
ddconfig_path: configs/ddconfigs/electricity.json

selected_columns: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196","197","198","199","200","201","202","203","204","205","206","207","208","209","210","211","212","213","214","215","216","217","218","219","220","221","222","223","224","225","226","227","228","229","230","231","232","233","234","235","236","237","238","239","240","241","242","243","244","245","246","247","248","249","250","251","252","253","254","255","256","257","258","259","260","261","262","263","264","265","266","267","268","269","270","271","272","273","274","275","276","277","278","279","280","281","282","283","284","285","286","287","288","289","290","291","292","293","294","295","296","297","298","299","300","301","302","303","304","305","306","307","308","309","310","311","312","313","314","315","316","317","318","319","320"] # should include all target column"," can include additional columns
target_columns: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196","197","198","199","200","201","202","203","204","205","206","207","208","209","210","211","212","213","214","215","216","217","218","219","220","221","222","223","224","225","226","227","228","229","230","231","232","233","234","235","236","237","238","239","240","241","242","243","244","245","246","247","248","249","250","251","252","253","254","255","256","257","258","259","260","261","262","263","264","265","266","267","268","269","270","271","272","273","274","275","276","277","278","279","280","281","282","283","284","285","286","287","288","289","290","291","292","293","294","295","296","297","298","299","300","301","302","303","304","305","306","307","308","309","310","311","312","313","314","315","316","317","318","319","320"]
target_column_types: # 'criterion' in training_spec must also be adapted
    "0": real
    "1": real
    "2": real
    "3": real
    "4": real
    "5": real
    "6": real
    "7": real
    "8": real
    "9": real
    "10": real
    "11": real
    "12": real
    "13": real
    "14": real
    "15": real
    "16": real
    "17": real
    "18": real
    "19": real
    "20": real
    "21": real
    "22": real
    "23": real
    "24": real
    "25": real
    "26": real
    "27": real
    "28": real
    "29": real
    "30": real
    "31": real
    "32": real
    "33": real
    "34": real
    "35": real
    "36": real
    "37": real
    "38": real
    "39": real
    "40": real
    "41": real
    "42": real
    "43": real
    "44": real
    "45": real
    "46": real
    "47": real
    "48": real
    "49": real
    "50": real
    "51": real
    "52": real
    "53": real
    "54": real
    "55": real
    "56": real
    "57": real
    "58": real
    "59": real
    "60": real
    "61": real
    "62": real
    "63": real
    "64": real
    "65": real
    "66": real
    "67": real
    "68": real
    "69": real
    "70": real
    "71": real
    "72": real
    "73": real
    "74": real
    "75": real
    "76": real
    "77": real
    "78": real
    "79": real
    "80": real
    "81": real
    "82": real
    "83": real
    "84": real
    "85": real
    "86": real
    "87": real
    "88": real
    "89": real
    "90": real
    "91": real
    "92": real
    "93": real
    "94": real
    "95": real
    "96": real
    "97": real
    "98": real
    "99": real
    "100": real
    "101": real
    "102": real
    "103": real
    "104": real
    "105": real
    "106": real
    "107": real
    "108": real
    "109": real
    "110": real
    "111": real
    "112": real
    "113": real
    "114": real
    "115": real
    "116": real
    "117": real
    "118": real
    "119": real
    "120": real
    "121": real
    "122": real
    "123": real
    "124": real
    "125": real
    "126": real
    "127": real
    "128": real
    "129": real
    "130": real
    "131": real
    "132": real
    "133": real
    "134": real
    "135": real
    "136": real
    "137": real
    "138": real
    "139": real
    "140": real
    "141": real
    "142": real
    "143": real
    "144": real
    "145": real
    "146": real
    "147": real
    "148": real
    "149": real
    "150": real
    "151": real
    "152": real
    "153": real
    "154": real
    "155": real
    "156": real
    "157": real
    "158": real
    "159": real
    "160": real
    "161": real
    "162": real
    "163": real
    "164": real
    "165": real
    "166": real
    "167": real
    "168": real
    "169": real
    "170": real
    "171": real
    "172": real
    "173": real
    "174": real
    "175": real
    "176": real
    "177": real
    "178": real
    "179": real
    "180": real
    "181": real
    "182": real
    "183": real
    "184": real
    "185": real
    "186": real
    "187": real
    "188": real
    "189": real
    "190": real
    "191": real
    "192": real
    "193": real
    "194": real
    "195": real
    "196": real
    "197": real
    "198": real
    "199": real
    "200": real
    "201": real
    "202": real
    "203": real
    "204": real
    "205": real
    "206": real
    "207": real
    "208": real
    "209": real
    "210": real
    "211": real
    "212": real
    "213": real
    "214": real
    "215": real
    "216": real
    "217": real
    "218": real
    "219": real
    "220": real
    "221": real
    "222": real
    "223": real
    "224": real
    "225": real
    "226": real
    "227": real
    "228": real
    "229": real
    "230": real
    "231": real
    "232": real
    "233": real
    "234": real
    "235": real
    "236": real
    "237": real
    "238": real
    "239": real
    "240": real
    "241": real
    "242": real
    "243": real
    "244": real
    "245": real
    "246": real
    "247": real
    "248": real
    "249": real
    "250": real
    "251": real
    "252": real
    "253": real
    "254": real
    "255": real
    "256": real
    "257": real
    "258": real
    "259": real
    "260": real
    "261": real
    "262": real
    "263": real
    "264": real
    "265": real
    "266": real
    "267": real
    "268": real
    "269": real
    "270": real
    "271": real
    "272": real
    "273": real
    "274": real
    "275": real
    "276": real
    "277": real
    "278": real
    "279": real
    "280": real
    "281": real
    "282": real
    "283": real
    "284": real
    "285": real
    "286": real
    "287": real
    "288": real
    "289": real
    "290": real
    "291": real
    "292": real
    "293": real
    "294": real
    "295": real
    "296": real
    "297": real
    "298": real
    "299": real
    "300": real
    "301": real
    "302": real
    "303": real
    "304": real
    "305": real
    "306": real
    "307": real
    "308": real
    "309": real
    "310": real
    "311": real
    "312": real
    "313": real
    "314": real
    "315": real
    "316": real
    "317": real
    "318": real
    "319": real
    "320": real


seq_length: 48
inference_batch_size: 10

export_onnx: true

model_spec:
  d_model: 64
  nhead: 4
  d_hid: 64
  nlayers: 4
training_spec:
  device: cuda
  epochs: 1000
  iter_save: 50
  batch_size: 200
  log_interval: 10
  lr: 0.0001
  accumulation_steps: 1
  dropout: 0.2
  criterion:
    "0": MSELoss
    "1": MSELoss
    "2": MSELoss
    "3": MSELoss
    "4": MSELoss
    "5": MSELoss
    "6": MSELoss
    "7": MSELoss
    "8": MSELoss
    "9": MSELoss
    "10": MSELoss
    "11": MSELoss
    "12": MSELoss
    "13": MSELoss
    "14": MSELoss
    "15": MSELoss
    "16": MSELoss
    "17": MSELoss
    "18": MSELoss
    "19": MSELoss
    "20": MSELoss
    "21": MSELoss
    "22": MSELoss
    "23": MSELoss
    "24": MSELoss
    "25": MSELoss
    "26": MSELoss
    "27": MSELoss
    "28": MSELoss
    "29": MSELoss
    "30": MSELoss
    "31": MSELoss
    "32": MSELoss
    "33": MSELoss
    "34": MSELoss
    "35": MSELoss
    "36": MSELoss
    "37": MSELoss
    "38": MSELoss
    "39": MSELoss
    "40": MSELoss
    "41": MSELoss
    "42": MSELoss
    "43": MSELoss
    "44": MSELoss
    "45": MSELoss
    "46": MSELoss
    "47": MSELoss
    "48": MSELoss
    "49": MSELoss
    "50": MSELoss
    "51": MSELoss
    "52": MSELoss
    "53": MSELoss
    "54": MSELoss
    "55": MSELoss
    "56": MSELoss
    "57": MSELoss
    "58": MSELoss
    "59": MSELoss
    "60": MSELoss
    "61": MSELoss
    "62": MSELoss
    "63": MSELoss
    "64": MSELoss
    "65": MSELoss
    "66": MSELoss
    "67": MSELoss
    "68": MSELoss
    "69": MSELoss
    "70": MSELoss
    "71": MSELoss
    "72": MSELoss
    "73": MSELoss
    "74": MSELoss
    "75": MSELoss
    "76": MSELoss
    "77": MSELoss
    "78": MSELoss
    "79": MSELoss
    "80": MSELoss
    "81": MSELoss
    "82": MSELoss
    "83": MSELoss
    "84": MSELoss
    "85": MSELoss
    "86": MSELoss
    "87": MSELoss
    "88": MSELoss
    "89": MSELoss
    "90": MSELoss
    "91": MSELoss
    "92": MSELoss
    "93": MSELoss
    "94": MSELoss
    "95": MSELoss
    "96": MSELoss
    "97": MSELoss
    "98": MSELoss
    "99": MSELoss
    "100": MSELoss
    "101": MSELoss
    "102": MSELoss
    "103": MSELoss
    "104": MSELoss
    "105": MSELoss
    "106": MSELoss
    "107": MSELoss
    "108": MSELoss
    "109": MSELoss
    "110": MSELoss
    "111": MSELoss
    "112": MSELoss
    "113": MSELoss
    "114": MSELoss
    "115": MSELoss
    "116": MSELoss
    "117": MSELoss
    "118": MSELoss
    "119": MSELoss
    "120": MSELoss
    "121": MSELoss
    "122": MSELoss
    "123": MSELoss
    "124": MSELoss
    "125": MSELoss
    "126": MSELoss
    "127": MSELoss
    "128": MSELoss
    "129": MSELoss
    "130": MSELoss
    "131": MSELoss
    "132": MSELoss
    "133": MSELoss
    "134": MSELoss
    "135": MSELoss
    "136": MSELoss
    "137": MSELoss
    "138": MSELoss
    "139": MSELoss
    "140": MSELoss
    "141": MSELoss
    "142": MSELoss
    "143": MSELoss
    "144": MSELoss
    "145": MSELoss
    "146": MSELoss
    "147": MSELoss
    "148": MSELoss
    "149": MSELoss
    "150": MSELoss
    "151": MSELoss
    "152": MSELoss
    "153": MSELoss
    "154": MSELoss
    "155": MSELoss
    "156": MSELoss
    "157": MSELoss
    "158": MSELoss
    "159": MSELoss
    "160": MSELoss
    "161": MSELoss
    "162": MSELoss
    "163": MSELoss
    "164": MSELoss
    "165": MSELoss
    "166": MSELoss
    "167": MSELoss
    "168": MSELoss
    "169": MSELoss
    "170": MSELoss
    "171": MSELoss
    "172": MSELoss
    "173": MSELoss
    "174": MSELoss
    "175": MSELoss
    "176": MSELoss
    "177": MSELoss
    "178": MSELoss
    "179": MSELoss
    "180": MSELoss
    "181": MSELoss
    "182": MSELoss
    "183": MSELoss
    "184": MSELoss
    "185": MSELoss
    "186": MSELoss
    "187": MSELoss
    "188": MSELoss
    "189": MSELoss
    "190": MSELoss
    "191": MSELoss
    "192": MSELoss
    "193": MSELoss
    "194": MSELoss
    "195": MSELoss
    "196": MSELoss
    "197": MSELoss
    "198": MSELoss
    "199": MSELoss
    "200": MSELoss
    "201": MSELoss
    "202": MSELoss
    "203": MSELoss
    "204": MSELoss
    "205": MSELoss
    "206": MSELoss
    "207": MSELoss
    "208": MSELoss
    "209": MSELoss
    "210": MSELoss
    "211": MSELoss
    "212": MSELoss
    "213": MSELoss
    "214": MSELoss
    "215": MSELoss
    "216": MSELoss
    "217": MSELoss
    "218": MSELoss
    "219": MSELoss
    "220": MSELoss
    "221": MSELoss
    "222": MSELoss
    "223": MSELoss
    "224": MSELoss
    "225": MSELoss
    "226": MSELoss
    "227": MSELoss
    "228": MSELoss
    "229": MSELoss
    "230": MSELoss
    "231": MSELoss
    "232": MSELoss
    "233": MSELoss
    "234": MSELoss
    "235": MSELoss
    "236": MSELoss
    "237": MSELoss
    "238": MSELoss
    "239": MSELoss
    "240": MSELoss
    "241": MSELoss
    "242": MSELoss
    "243": MSELoss
    "244": MSELoss
    "245": MSELoss
    "246": MSELoss
    "247": MSELoss
    "248": MSELoss
    "249": MSELoss
    "250": MSELoss
    "251": MSELoss
    "252": MSELoss
    "253": MSELoss
    "254": MSELoss
    "255": MSELoss
    "256": MSELoss
    "257": MSELoss
    "258": MSELoss
    "259": MSELoss
    "260": MSELoss
    "261": MSELoss
    "262": MSELoss
    "263": MSELoss
    "264": MSELoss
    "265": MSELoss
    "266": MSELoss
    "267": MSELoss
    "268": MSELoss
    "269": MSELoss
    "270": MSELoss
    "271": MSELoss
    "272": MSELoss
    "273": MSELoss
    "274": MSELoss
    "275": MSELoss
    "276": MSELoss
    "277": MSELoss
    "278": MSELoss
    "279": MSELoss
    "280": MSELoss
    "281": MSELoss
    "282": MSELoss
    "283": MSELoss
    "284": MSELoss
    "285": MSELoss
    "286": MSELoss
    "287": MSELoss
    "288": MSELoss
    "289": MSELoss
    "290": MSELoss
    "291": MSELoss
    "292": MSELoss
    "293": MSELoss
    "294": MSELoss
    "295": MSELoss
    "296": MSELoss
    "297": MSELoss
    "298": MSELoss
    "299": MSELoss
    "300": MSELoss
    "301": MSELoss
    "302": MSELoss
    "303": MSELoss
    "304": MSELoss
    "305": MSELoss
    "306": MSELoss
    "307": MSELoss
    "308": MSELoss
    "309": MSELoss
    "310": MSELoss
    "311": MSELoss
    "312": MSELoss
    "313": MSELoss
    "314": MSELoss
    "315": MSELoss
    "316": MSELoss
    "317": MSELoss
    "318": MSELoss
    "319": MSELoss
    "320": MSELoss
  optimizer:
    name: AdamW
  scheduler:
    name: CosineAnnealingLR
    T_max: 1100
    eta_min: 0.000001
  continue_training: true